name: Rust

on:
  push:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "CODE_OF_CONDUCT.md"
      - "SECURITY.md"
      - ".github/**"
      - "docs/**"
      - "examples/**"
      - "tests/**"
      - "benches/**"

  pull_request:
    branches: ["master"]
    paths-ignore:
      - "README.md"
      - "LICENSE"
      - "CONTRIBUTING.md"
      - "CODE_OF_CONDUCT.md"
      - "SECURITY.md"
      - ".github/**"
      - "docs/**"
      - "examples/**"
      - "tests/**"
      - "benches/**"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose

      - name: Run benchmarks
        run: cargo bench --verbose
